{% set version = "2.0.2" %}

package:
  name: crispritz
  version: {{ version }}

source:
  url: https://github.com/pinellolab/CRISPRitz/archive/v{{ version }}.tar.gz
  sha256: 16c8842433c34696fdd641f60d1bced8b9e3bed10ca046df7c14c6cff9a299c3
 
build:
  number: 0

requirements:
  build:
    - {{compiler('cxx')}}
    - make
    - boost
    - openmp
    
  host:
    - bedtools
    - scikit-learn =0.21.2
    - biopython
    - intervaltree
    - matplotlib
    - pandas
    - scipy
    - numpy
    - more-itertools
    - statsmodels
    - bcftools
    - boost
    - tk
    - openmp
    - libdeflate
    - libcxx
    - python =3.6
    
  run:
    - bedtools
    - scikit-learn =0.21.2
    - biopython
    - intervaltree
    - matplotlib
    - pandas
    - scipy
    - numpy
    - more-itertools
    - statsmodels
    - bcftools
    - boost
    - tk
    - openmp
    - libdeflate
    - libcxx
    - python =3.6
    
test:
  commands:
    - crispritz.py

about:
  home: https://github.com/pinellolab/CRISPRitz
  license: GPL3
  summary: CRISPRitz, tool package for CRISPR experiments assessment and analysis.
