{% set version = "2.0.1" %}

package:
  name: crispritz
  version: {{ version }}

source:
  url: https://github.com/pinellolab/CRISPRitz/archive/v{{ version }}.tar.gz
  sha256: cfe990a2763b4b3f7f535848d05f42b7379ac8a908f7e852f680ab70968d9d41
 
build:
  number: 0

requirements:
  build:
    - {{compiler('cxx')}}
    - make
    - boost
    - openmp
    
  host:
    - bedtools
    - scikit-learn =0.21.2
    - biopython
    - intervaltree
    - matplotlib
    - pandas
    - scipy
    - numpy
    - more-itertools
    - statsmodels
    - bcftools
    - boost
    - tk
    - openmp
    - libdeflate
    - libcxx
    - python =3.6
    
  run:
    - bedtools
    - scikit-learn =0.21.2
    - biopython
    - intervaltree
    - matplotlib
    - pandas
    - scipy
    - numpy
    - more-itertools
    - statsmodels
    - bcftools
    - boost
    - tk
    - openmp
    - libdeflate
    - libcxx
    - python =3.6
    
test:
  commands:
    - crispritz.py

about:
  home: https://github.com/pinellolab/CRISPRitz
  license: GPL3
  summary: CRISPRitz, tool package for CRISPR experiments assessment and analysis.
