package:
  name: phylocsf
  version: "1.0.0"

build:
  number: 0
  script_env:
    - LD_LIBRARY_PATH # [linux]
    - DYLD_LIBRARY_PATH # [osx]

source:
  url: https://github.com/RomainFeron/PhyloCSF/archive/1.0.1-conda.tar.gz
  sha256: 8c356198beb7ca39a50359748484499d70255f42adfcd144760cf28d57be5135

requirements:
  build:
    - {{ compiler('cxx') }}
    - glpk
    - gsl
    - m4
    - pkg-config
    - ocaml
    - unzip
    - wget
  run:
    - gsl
    - ocaml

# The best way to test would be to use a test dataset present in the tarball
# This does not work during the container test though, so for now it's disabled
# test:
#   commands:
#     - PhyloCSF 2>&1

about:
  home: https://github.com/mlin/PhyloCSF/wiki
  license: AGPL-3.0
  summary: Phylogenetic analysis of multi-species genome sequence alignments to identify conserved protein-coding regions

extra:
  identifiers:
    - biotools:phyloCSF
