package:
  name: phylocsf
  version: "1.0.0"

build:
  number: 0

source:
  url: https://github.com/RomainFeron/PhyloCSF/archive/1.0.0-conda.tar.gz
  sha256: 92d7cda22636a5f56b58332604d99276a273b67d0770cf9760d064200a83e188

requirements:
  build:
    - {{ compiler('c') }}
    - ocaml
    - wget
  run:

test:
  commands:
    - PhyloCSF > /dev/null

about:
  home: https://github.com/mlin/PhyloCSF/wiki
  license: AGPL-3.0
  summary: Phylogenetic analysis of multi-species genome sequence alignments to identify conserved protein-coding regions

extra:
  identifiers:
    - biotools:phyloCSF
