{% set version = "0.6.7" %}
{% set github = "https://github.com/hbc/bcbioBase" %}

package:
  name: r-bcbiobase
  version: "{{version}}"

source:
  url: "{{ github }}/archive/v{{ version }}.tar.gz"
  sha256: 3a886d3c32cf60f6d11c916d85105d19176a36f2df1699259e5b223e07097031

build:
  number: 0
  noarch: generic
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - bioconductor-biostrings
    - bioconductor-s4vectors
    - r-base
    - r-basejump >=0.11
    - r-dplyr >=0.8
    - r-goalie >=0.2.19
    - r-magrittr >=1.5
    - r-plyr >=1.8
    - r-rdrop2 >=0.8
    - r-readr >=1.3
    - r-rlang >=0.4
    - r-stringr >=1.3
    - r-tibble >=2.1
    - r-tidyr >=0.8

  run:
    - bioconductor-biostrings
    - bioconductor-s4vectors
    - r-base
    - r-basejump >=0.11
    - r-dplyr >=0.8
    - r-goalie >=0.2.19
    - r-magrittr >=1.5
    - r-plyr >=1.8
    - r-rdrop2 >=0.8
    - r-readr >=1.3
    - r-rlang >=0.4
    - r-stringr >=1.3
    - r-tibble >=2.1
    - r-tidyr >=0.8

test:
  commands:
    - $R -e "library('bcbioBase')"

about:
  home: http://bioinformatics.sph.harvard.edu/bcbioBase/
  dev_url: "{{ github }}"
  license: MIT
  summary: Base functions and generics for bcbio R packages.

extra:
  recipe-maintainers:
    - mjsteinbaugh
    - roryk
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
