{% set version = "0.3.22" %}
{% set github = "https://github.com/hbc/bcbioRNASeq" %}

package:
  name: r-bcbiornaseq
  version: "{{ version }}"

source:
  url: "https://github.com/hbc/bcbioRNASeq/archive/v{{ version }}.tar.gz"
  sha256: 6150eaf3df6c3c48ded543266e12131aea926d84b555af96128ce2362542feae

build:
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    # Depends:
    - r-base
    - bioconductor-summarizedexperiment >=1.14.0
    - r-basejump >=0.11.1
    # Imports:
    - r-acidplots >=0.2.7
    - r-bcbiobase >=0.6.7
    - r-bioverbs >=0.2.0
    - r-deseqanalysis >=0.2.0
    - r-goalie >=0.2.19
    - bioconductor-biocgenerics
    - bioconductor-degreport >=1.19.1
    - bioconductor-deseq2 >=1.22.1
    - bioconductor-edger >=3.26.5
    - bioconductor-genomicfeatures
    - bioconductor-s4vectors
    - bioconductor-tximport >=1.12.3
    - bioconductor-vsn >=3.52.0
    - r-cowplot >=1.0
    - r-dplyr >=0.8
    - r-ggplot2 >=3.2
    - r-ggrepel >=0.8
    - r-knitr >=1.23
    - r-magrittr >=1.5
    - r-readr >=1.3
    - r-rlang >=0.4
    - r-scales >=1.0
    - r-sessioninfo >=1.1
    - r-stringr >=1.4
    - r-tibble >=2.1
    # Suggests:
    - bioconductor-biocparallel
    - bioconductor-biocstyle
    - bioconductor-clusterprofiler >=3.10.1
    - bioconductor-dose >=3.8.0
    - bioconductor-ensdb.hsapiens.v75
    - bioconductor-genomeinfodbdata
    - bioconductor-org.hs.eg.db
    - bioconductor-org.mm.eg.db
    - bioconductor-pathview >=1.22.0
    - bioconductor-rhdf5 >=2.28.0
    - r-hexbin >=1.27.3
    - r-pbapply >=1.4
    - r-rmarkdown >=1.0
    - r-tidyverse >=1.2.1
    - r-viridis >=0.5.1

  run:
    # Depends:
    - r-base
    - bioconductor-summarizedexperiment >=1.14.0
    - r-basejump >=0.11.1
    # Imports:
    - r-acidplots >=0.2.7
    - r-bcbiobase >=0.6.7
    - r-bioverbs >=0.2.0
    - r-deseqanalysis >=0.2.0
    - r-goalie >=0.2.19
    - bioconductor-biocgenerics
    - bioconductor-degreport >=1.19.1
    - bioconductor-deseq2 >=1.22.1
    - bioconductor-edger >=3.26.5
    - bioconductor-genomicfeatures
    - bioconductor-s4vectors
    - bioconductor-tximport >=1.12.3
    - bioconductor-vsn >=3.52.0
    - r-cowplot >=1.0
    - r-dplyr >=0.8
    - r-ggplot2 >=3.2
    - r-ggrepel >=0.8
    - r-knitr >=1.23
    - r-magrittr >=1.5
    - r-readr >=1.3
    - r-rlang >=0.4
    - r-scales >=1.0
    - r-sessioninfo >=1.1
    - r-stringr >=1.4
    - r-tibble >=2.1
    # Suggests:
    - bioconductor-biocparallel
    - bioconductor-biocstyle
    - bioconductor-clusterprofiler >=3.10.1
    - bioconductor-dose >=3.8.0
    - bioconductor-ensdb.hsapiens.v75
    - bioconductor-genomeinfodbdata
    - bioconductor-org.hs.eg.db
    - bioconductor-org.mm.eg.db
    - bioconductor-pathview >=1.22.0
    - bioconductor-rhdf5 >=2.28.0
    - r-hexbin >=1.27.3
    - r-pbapply >=1.4
    - r-rmarkdown >=1.0
    - r-tidyverse >=1.2.1
    - r-viridis >=0.5.1

test:
  commands:
    - $R -e "library('bcbioRNASeq')"

about:
  home: http://bioinformatics.sph.harvard.edu/bcbioRNASeq/
  dev_url: "{{ github }}"
  license: MIT
  summary: R package for bcbio RNA-seq analysis.

extra:
  recipe-maintainers:
    - mjsteinbaugh
    - roryk
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
