package:
  name: r-bcbiornaseq

  version: "0.3.22"

source:
  url: https://github.com/hbc/bcbioRNASeq/archive/v0.3.22.tar.gz
  sha256: 6150eaf3df6c3c48ded543266e12131aea926d84b555af96128ce2362542feae

build:
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - bioconductor-summarizedexperiment
    - r-bcbiobase
    - bioconductor-deseq2
    - bioconductor-degreport
    - bioconductor-edger
    - r-ggrepel
    - r-pbapply
    - bioconductor-tximport
    - bioconductor-vsn
    - r-rmarkdown
    - r-tidyverse
    - bioconductor-genomeinfodbdata
    - r-hexbin

  run:
    - r-base
    - bioconductor-summarizedexperiment
    - r-bcbiobase
    - bioconductor-deseq2
    - bioconductor-degreport
    - bioconductor-edger
    - r-ggrepel
    - r-pbapply
    - bioconductor-tximport
    - bioconductor-vsn
    - r-rmarkdown
    - r-tidyverse
    - bioconductor-genomeinfodbdata
    - r-hexbin

test:
  commands:
    - $R -e "library('bcbioRNASeq')"

about:
  home: https://github.com/hbc/bcbioRNASeq
  license: MIT
  summary: Quality control and differential expression for bcbio RNA-seq experiments.
extra:
  recipe-maintainers:
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - roryk
