{% set name = "transit" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mad-lab/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 3d2a300ec5b9beb4bc1ba97b5bb9e5258d52ac5fe7474bcaad3ce377db4ae00f

build:
  number: 0
  script: "python setup.py install --single-version-externally-managed --record=record.txt"
  noarch: python
  
requirements:
  build:
    - python <3
    - numpy >=1.15
    - scipy >=1.1
    - matplotlib >=2.2
    - pillow ==5.0
    - statsmodels >=0.9
  run:
    - python <3
    - numpy >=1.15
    - scipy >=1.1
    - matplotlib >=2.2
    - pillow ==5.0
    - statsmodels >=0.9

test:
  commands:
    - transit

about:
  home: http://github.com/mad-lab/transit
  license: GPL-3
  license_family: GPL
  license_file: LICENSE.md
  summary: 'TRANSIT'
  description: |
    TRANSIT is a software that can be used to analyze Tn-Seq datasets.
    It includes various statistical calculations of essentiality of
    genes or genomic regions (including conditional essentiality
    between 2 conditions).
  dev_url: https://github.com/simongog/sdsl-lite
